name: Spell Check

on: [push, pull_request]

jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install codespell
      run: pip install codespell

    - name: Run codespell
      run: codespell --ignore-words=codespell_ignore.txt **/*
